# Generated by Django 6.0.5 on 2026-05-24 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePaperORM',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('article_title', models.TextField(blank=True, null=True)),
                ('article_introduction', models.TextField(blank=True, null=True)),
                ('article_chapters_name', models.JSONField(blank=True, null=True)),
                ('article_chapters_contents', models.JSONField(blank=True, null=True)),
                ('final_article', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problems', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromtTemplateORM',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('started', 'STARTED'), ('generate_title', 'GENERATE_TITLE'), ('generate_introduction', 'GENERATE_INTRODUCTION'), ('generate_chapters_name', 'GENERATE_CHAPTERS_NAME'), ('generate_chapters_content', 'GENERATE_CHAPTERS_CONTENT'), ('merge_article', 'MERGE_ARTICLE'), ('seo_fix', 'SEO_FIX')], max_length=255)),
                ('template', models.TextField(help_text='\n<br> Здесь пишется шаблон промпта для генерации. В шаблон можно использовать следующие переменные:\n<br>\n<br> - marker: маркер статьи (смысл статьи)\n<br> - depth: глубина статьи (ключевые слова)\n<br> - width: ширина статьи (доп ключевые слова)\n<br> - n_gramms: n-граммы статьи \n<br> - count_chapters: количество глав статьи\n<br> - about_author: о авторе статьи\n<br> - chapter_index: номер текущей главы\n<br><br> ! На момент заполнения шаблона переменные ниже могут еще не существовать, в этом случае будут пустые строки !\n<br> - article_title: заголовок статьи \n<br> - article_introduction: введение статьи \n<br> - article_chapters_name: названия глав статьи (после шага generate_chapters_name)\n<br> - article_chapters_content: содержимое глав статьи (после шага generate_chapters_content)\n<br> - final_article: финальная статья (после шага merge)\n<br> - problems: SEO-проблемы статьи (после шага merge)\n<br><br> Подставлять значения переменных нужно в таком виде: текст {переменная} текст\n')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleProjectORM',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('marker', models.TextField()),
                ('depth', models.JSONField()),
                ('width', models.JSONField()),
                ('n_gramms', models.JSONField()),
                ('count_chapters', models.IntegerField()),
                ('about_author', models.TextField()),
                ('status', models.TextField(choices=[('NEW', 'new'), ('NOT_STARTED', 'not_started'), ('STARTED', 'started'), ('GENERATE_TITLE', 'generate_title'), ('GENERATE_INTRODUCTION', 'generate_introduction'), ('GENERATE_CHAPTERS_NAME', 'generate_chapters_name'), ('GENERATE_CHAPTERS_CONTENT', 'generate_chapters_content'), ('MERGE_ARTICLE', 'merge_article'), ('SEO_FIX', 'seo_fix'), ('COMPLETED', 'completed'), ('CANCELLED', 'cancelled'), ('ERROR', 'error')], db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article_paper', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.articlepaperorm')),
            ],
        ),
    ]
